name: Build and Push Docker Image

on:
  push:
    branches:
      - main # só dispara quando fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login no Docker Hub usando os secrets configurados no GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Buildar e publicar a imagem no Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/colo-de-deus-api:latest
