name: Build and Push Docker Image

on:
  push:
    branches:
      - main # só dispara quando fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js (opcional, útil se precisar rodar npm build antes do Docker)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Login no Docker Hub usando os secrets configurados no GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Buildar e publicar a imagem no Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/colo-de-deus-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/colo-de-deus-api:latest
          cache-to: type=inline

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/docker-compose
            docker-compose pull
            docker-compose up -d
